FROM rocker/tidyverse

RUN mkdir -p /home/rstudio/.rstudio
RUN chmod 0777 /home/rstudio/.rstudio

RUN install2.r --error \
    --deps TRUE \
    DALEX \
    abind \ 
    ade4 \ 
    amap \ 
    askpass \ 
    assertthat \ 
    backports \ 
    base \ 
    base64enc \ 
    bayesSurv \ 
    BBmisc \ 
    BH \ 
    bit \ 
    bit64 \ 
    bitops \ 
    blob \ 
    boot \ 
    brazilmaps-master \ 
    brew \ 
    broom \ 
    callr \ 
    car \ 
    carData \ 
    caret \ 
    caTools \ 
    cellranger \ 
    checkmate \ 
    chron \ 
    class \ 
    classInt \ 
    cli \ 
    clipr \ 
    clisymbols \ 
    cluster \ 
    coda \ 
    codetools \ 
    colorspace \ 
    commonmark \ 
    compiler \ 
    config \ 
    covr \ 
    cowplot \ 
    crayon \ 
    crosstalk \ 
    curl \ 
    data.table \ 
    datasets \ 
    DBI \ 
    dbplyr \ 
    dendextend \ 
    desc \ 
    devtools \ 
    digest \ 
    dplyr \ 
    DT \ 
    e1071 \ 
    ellipse \ 
    ellipsis \ 
    evaluate \ 
    factoextra \ 
    FactoMineR \ 
    fansi \ 
    farver \ 
    fastDummies \ 
    fastGHQuad \ 
    fastmap \ 
    fastmatch \ 
    ff \ 
    flashClust \ 
    flextable \ 
    fontBitstreamVera \ 
    fontLiberation \ 
    fontquiver \ 
    forcats \ 
    foreach \ 
    foreign \ 
    forge \ 
    fs \ 
    gdata \ 
    gdtools \ 
    generics \ 
    ggforce \ 
    ggiraph \ 
    ggiraphExtra \ 
    ggplot2 \ 
    ggpubr \ 
    ggrepel \ 
    ggsci \ 
    ggsignif \ 
    ggthemes \ 
    gh \ 
    git2r \ 
    glue \ 
    gower \ 
    gplots \ 
    graphics \ 
    grDevices \ 
    grid \ 
    gridExtra \ 
    gsubfn \ 
    gtable \ 
    gtools \ 
    haven \ 
    highr \ 
    hms \ 
    htmltools \ 
    htmlwidgets \ 
    httpuv \ 
    httr \ 
    Icens \ 
    icensBKL \ 
    ini \ 
    insight \ 
    installr \ 
    interval \ 
    ipred \ 
    ISLR \ 
    iterators \ 
    jsonlite \ 
    KernSmooth \ 
    knitr \ 
    labeling \ 
    later \ 
    lattice \ 
    lava \ 
    lazyeval \ 
    leaps \ 
    lifecycle \ 
    lme4 \ 
    logspline \ 
    lubridate \ 
    magrittr \ 
    maptools \ 
    markdown \ 
    MASS \ 
    Matrix \ 
    MatrixModels \ 
    memoise \ 
    methods \ 
    mgcv \ 
    mime \ 
    minqa \ 
    mixAK \ 
    MLEcens \ 
    mlr \ 
    mnormt \ 
    ModelMetrics \ 
    modelr \ 
    moonBook \ 
    munsell \ 
    mvtnorm \ 
    mycor \ 
    nlme \ 
    nloptr \ 
    nnet \ 
    nortest \ 
    numDeriv \ 
    officer \ 
    openssl \ 
    openxlsx \ 
    parallel \ 
    parallelMap \ 
    ParamHelpers \ 
    pbkrtest \ 
    perm \ 
    pillar \ 
    pkgbuild \ 
    pkgconfig \ 
    pkgload \ 
    plogr \ 
    plyr \ 
    polyclip \ 
    polynom \ 
    PortfolioOptim \ 
    ppcor \ 
    praise \ 
    prettyunits \ 
    processx \ 
    prodlim \ 
    progress \ 
    promises \ 
    proto \ 
    ps \ 
    psych \ 
    purrr \ 
    qtl \ 
    quantreg \ 
    r2d3 \ 
    R6 \ 
    rappdirs \ 
    rcmdcheck \ 
    RColorBrewer \ 
    Rcpp \ 
    RcppEigen \ 
    readr \ 
    readxl \ 
    recipes \ 
    rematch \ 
    remotes \ 
    reprex \ 
    reshape \ 
    reshape2 \ 
    reticulate \ 
    rex \ 
    rio \ 
    rlang \ 
    rmarkdown \ 
    roxygen2 \ 
    rpart \ 
    rprojroot \ 
    RSQLite \ 
    rstudioapi \ 
    Rsymphony \ 
    Rtsne \ 
    rversions \ 
    rvest \ 
    scales \ 
    scatterplot3d \ 
    selectr \ 
    sessioninfo \ 
    sf-master \ 
    shiny \ 
    shinyjs \ 
    showtext \ 
    showtextdb \ 
    sjlabelled \ 
    sjmisc \ 
    smoothSurv \ 
    sourcetools \ 
    sp \ 
    sparklyr \ 
    SparseM \ 
    spatial \ 
    splines \ 
    splitstackshape \ 
    sqldf \ 
    SQUAREM \ 
    stats \ 
    stats4 \ 
    stringi \ 
    stringr \ 
    survival \ 
    sys \ 
    sysfonts \ 
    systemfonts \ 
    tcltk \ 
    TeachingDemos \ 
    tensorflow \ 
    testthat \ 
    tfruns \ 
    tibble \ 
    tidyr \ 
    tidyselect \ 
    tidyverse \ 
    timeDate \ 
    tinytex \ 
    tools \ 
    translations \ 
    tree \ 
    tweenr \ 
    units \ 
    usethis \ 
    utf8 \ 
    utils \ 
    uuid \ 
    vctrs \ 
    viridis \ 
    viridisLite \ 
    webshot \ 
    whisker \ 
    withr \ 
    xfun \ 
    xgboost \ 
    XML \ 
    xml2 \ 
    xopen \ 
    xtable \ 
    yaml \ 
    zeallot \ 
    zip 
